name: Build Test
on:
  push:
    branches:
        - main
        - 'develop'
        - 'feature/**'
        - 'test/**'
  pull_request:
    branches:
        - main
        - 'develop'
        - 'feature/**'

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: '14.2'
      
    - uses: actions/checkout@v3
    
    - name: Build Xcode
      run: |
        xcodebuild clean build -project FanFollow/FanFollow.xcodeproj -scheme FanFollow -destination "platform=iOS Simulator,name=iPhone 11 Pro,OS=latest"
        
    - name: Unit Test Build
      run: |
        xcodebuild clean build-for-testing -project FanFollow/FanFollow.xcodeproj -scheme FanFollow -destination "platform=iOS Simulator,name=iPhone 11 Pro,OS=latest"
        
    - name: Unit Testing
      run : |
        xcodebuild test-without-building -scheme FanFollow -project FanFollow/FanFollow.xcodeproj -destination "platform=iOS Simulator, name=iPhone 11 Pro,OS=latest"
