name: Build Test
on:
  push:
    branches:
        - main
        - 'develop'
        - 'feature/**'
  pull_request:
    branches:
        - main
        - 'develop'
        - 'feature/**'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Xcode
      run: |
        xcodebuild clean test -project FanFollow/FanFollow.xcodeproj \
        -scheme FanFollow \
        -destination 'platform=iOS Simulator,name=iPhone 13,OS=latest'
