name: Build Test
on:
  push:
    branches:
        - main
        - 'develop'
        - 'feature/**'
        - 'test/**'
  pull_request:
    branches:
        - main
        - 'develop'
        - 'feature/**'

jobs:
  build:
    runs-on: macos-latest
    
    env:
        PROJECT: FanFollow/FanFollow.xcodeproj
        SCHEME: Default
        DESTINATION: platform=iOS Simulator,name=iPhone 13,OS=14.0.1
        CONFIGURATION: Debug

    steps:
    - name: Checkout
    - uses: actions/checkout@v2
    
    - name: Build Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app
    - name: Install xcpretty
        run: sudo gem install xcpretty
    - name: XcodeBuild Clean Test
        run: xcodebuild clean test
            - project "$PROJECT"
            - scheme "$SCHEME"
            - destination: "$DESTINATION"
            - configuration "$CONFIGURATION"
            - enableCodeCoverage YES | xcpretty --color
            - showBuildTimingSummary
